### ISSUE TITLE
Question about the rendering speed

### ISSUE THREAD

**Issue by yuzewang1998** [jkulhanek/wild-gaussians#20]
Hi, 
This is an amazing piece of work,  congratuations! I have a question about the rendering speed. 
When I use the following command to render the test set:
```
nerfbaselines render --checkpoint ./0trevi-checkpoint-200000 --data /DATA/UBUNTU_data/dataset/PT-nbstyle/phototourism/trevi-fountain/

```
The rendering speed seems slow—it took around 3 minutes and 24 seconds to render 19 images on an RTX 4090 with a downscale factor of 2.

May I kindly ask if you have any suggestions or insights on how I might be able to achieve real-time rendering performance, as mentioned in the paper?

Thank you so much for your time and help! I greatly appreciate any advice you can offer.

**Comment by jkulhanek** [comment]
Hi, thank you for your interest!

1) please note, that the render command performs appearance optimization (according to the nerfw eval protocol) for each image before rendering - that is the reason why it is so slow. Try render-trajectory command. In the viewer, you can create a trajectory and even set different appearance embedding for different keyframes such that you can see the method interpolating between the appearances. After saving trajectory.jsonfile, you can render it using render-trajectory command. Btw, in the viewer you should also see real-time rendering performance.
2) To get >100FPS, we perform appearance caching, but this is not yet part of the released code. However, even without the caching you should have fps >60 on 4090. We also disabled depth rendering (which makes the method 2x slower as it needs two separate rendering passes).
3) older version of nerfbaselines had overhead for each rendered frame of 50ms due to slow pickle serialization needed for conda/docked/apptainer backend. This is not the case if you installed the method locally or if you have the newest nerfbaselines method (which uses shared memory and overhead is 2-4ms per frame). Also, the newest version of nerfbaselines supports disabling depth rendering (not yet merged in the wg repo), so after merging you wouldn’t need to disable depth rendering manually - it will be disabled automatically if you don’t need it. Note, that the render command (apart of optimizing appearances) always render everything including expected depths.

**Comment by yuzewang1998** [comment]
Hi, @jkulhanek,
Thank you for your detailed reply! Congratulations on having WildGaussians accepted at NeurIPS 2025! That’s truly impressive work.
